language: node_js
node_js:
  - node
  - '7'
  - '6'
cache: yarn

branches:
  only:
    - master

# Start X for acceptance testing
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - "export NODE_ENV=production"
